'''
problem

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fibonacci():
    array = [1]
    while array[-1] <= 4000000:
        if len(array) < 2:
           array.append(2)
        else:
            add_num = array[-1] + array[-2]
            array.append(add_num)
    return array

def sum_of_even_numbers(num_arr):
    create_array = []
    for numbers_given in num_arr:
        if numbers_given%2 == 0:
            create_array.append(numbers_given)
    return sum(create_array)


new_array = fibonacci()
print(sum_of_even_numbers(new_array))